version: "3.8"
services:
  getjob:
    build: .
    image: "github.com/quangdangfit/getjob"
    ports:
      - "8080:8080"
    environment:
      DATABASE__HOST: "mysql"
    depends_on:
      - mysql
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "/.storage/redis_data:/data"

  mysql:
    restart: always
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - "./storage/mysql_data/data:/var/lib/mysql"
      - "./scripts/initdb.d:/docker-entrypoint-initdb.d"

